### ISSUE TITLE
"Negative" numbers

### ISSUE THREAD

**Issue by kobigurk** [str4d/zk#1]
To make the r1cs format transferable between fields of different characteristics, we may need to account for negative numbers. I've seen some constraints relying on the wrapping-around property when subtracting, for example.

@str4d what do you think would be a good advancement here? Is introducing negative numbers in the file format the right way?

**Comment by str4d** [comment]
The file format uses SignedVarInt almost everywhere (only places it isn't used are the version and lengths of arrays, neither of which make sense to ever be negative). In particular, the coefficients of variables can have a sign. So I believe what you are after is already supported.

There are two related issues:

- Canonicity: -1 == char - 1 in a finite field, so it's possible to write the exact same constraints in different ways on-disk. This can make it trickier to figure out whether two circuits are the same. I've been discussing solutions to this with Thibaut Schaeffer, and our current plan is to write a spec describing how to take a generic circuit and compute several layers of "hashes", to enable checking whether two circuits are identical at some level.

- Size: for a 256-bit field, in a SignedVarInt, -1 is one byte, while in both signed and unsigned VarInt char - 1 is 37 bytes. This was the original reason for supporting negative coefficients - it greatly reduces the filesize when you have many small positive or negative coefficients, which do occur in constraints as a matter of course.

**Comment by kobigurk** [comment]
Great! SignedVarInt does indeed answer the simpler requirement I mentioned, at least on the decoding side.
On the encoding side, if we'd like the existing front-ends to be also transfer-friendly, it requires them to use negative integers when they save their constraint system, which libsnark, for example, doesn't do. Not sure about bellman. @madars @ebfull?

@schaeff also discussed in some chats the fact that circuits may be the same for other reasons (i.e., a=5,b=x,10 is the same as a=1,b=5x,c=10). I guess the plan is to account for these as well?

**Comment by str4d** [comment]
What I do when decoding in the reference implementation, is hard-code `char - i -> -i` for `i = [1, 10]` (which then means when encoding again, those get written as negatives). This seems like a reasonable trade-off between readability and re-encoding size, and accidentally interpreting a truly-random value as a small negative. We could do a similar thing by convention when encoding, or extend the internal representations to distinguish small negative coefficients and remember them. Bellman does not support negative coefficients currently, as they are all field elements internally and therefore in the scalar field.

Re: accounting for different representations of identical constraints: yes that's something we'd want the spec to cover. It's the hardest of the three cases to handle (the other two being canonical linear combinations, and canonical ordering of constraints), but I have a few ideas for how to possibly approach it.

**Comment by kobigurk** [comment]
Yeah, I saw the negative decoding logic, which makes sense to me as well.
I'll give it some more thought - maybe a more abstract layer above the internal field element representation would be beneficial. Thanks for the comments!
